/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.0/userguide/multi_project_builds.html
 */
rootProject.name = "govern-service"

include(":discovery")
include(":config")
include(":core")
include(":bom")
include(":dependencies")
include(":spring-cloud-govern-core")
include(":spring-cloud-starter-discovery")
include(":spring-cloud-starter-config")
include(":rest-api")

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("io.codearte.gradle.nexus:gradle-nexus-staging-plugin:0.30.0")
    }
}


