/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.ahoo.govern.discovery;

import me.ahoo.govern.core.Namespaced;

import java.util.List;
import java.util.Set;
import java.util.concurrent.CompletableFuture;

/**
 * @author ahoo wang
 */
public interface ServiceDiscovery {

    CompletableFuture<Set<String>> getServices(String namespace);

    CompletableFuture<Set<String>> getServices();

    CompletableFuture<List<ServiceInstance>> getInstances(String serviceId);

    CompletableFuture<List<ServiceInstance>> getInstances(String namespace, String serviceId);

}
