/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.ahoo.govern.discovery;

import java.util.List;
import java.util.Set;
import java.util.concurrent.CompletableFuture;

/**
 *
 * @author ahoo wang
 */
public interface ServiceDiscovery {

    CompletableFuture<Set<String>>  getServices();

    CompletableFuture<List<ServiceInstance>> getInstances(String serviceId);

}
