spring:
  cloud:
    cosky:
      discovery:
        registry:
          weight: 8

  web:
    resources:
      static-locations: file:./cosky-dashboard/dist/dashboard/
  webflux:
    static-path-pattern: /dashboard/**
cosky:
  security:
    enabled: true
    audit-log:
      action: write
    enforce-init-super-user: ${cosky.super.init:true}

cosec:
  jwt:
    algorithm: hmac256
    secret: ${cosky.security.key:FyN0Igd80Gas3stTavArGKOYnS9uLWGA$}
    token-validity:
      access: 15m
      refresh: 3H
cosid:
  namespace: ${spring.application.name}
  machine:
    enabled: true
    distributor:
      type: redis
  snowflake:
    enabled: true
    share:
      converter:
        type: radix
  segment:
    enabled: false
simba:
  redis:
    enabled: true
logging:
  file:
    name: logs/${spring.application.name}.log
