spring:
  cloud:
    cosky:
      discovery:
        registry:
          weight: 8

  web:
    resources:
      static-locations: file:./cosky-dashboard/dist/dashboard/
  webflux:
    static-path-pattern: /dashboard/**
cosky:
  security:
    enabled: true
    audit-log:
      action: write
    jwt:
      signing-key: ${cosky.security.key:FyN0Igd80Gas3stTavArGKOYnS9uLWGA$}
      access-token-validity: 15m
      refresh-token-validity: 3H
    enforce-init-super-user: false

cosid:
  namespace: ${spring.application.name}
  snowflake:
    enabled: true
    machine:
      distributor:
        type: redis
simba:
  redis:
    enabled: true
