spring:
  cloud:
    cosky:
      discovery:
        registry:
          weight: 8

  web:
    resources:
      static-locations: file:./cosky-dashboard/dist/dashboard/
  webflux:
    static-path-pattern: /dashboard/**

cosky:
  security:
    enabled: true
    audit-log:
      action: write
    jwt:
      signing-key: ${cosky.security.key:FyN0Igd80Gas3stTavArGKOYnS9uLWGA$}
      access-token-validity: 15m
      refresh-token-validity: 3H
    enforce-init-super-user: ${cosky.super.init:true}

cosid:
  namespace: ${spring.application.name}
  machine:
    enabled: true
    distributor:
      type: redis
  snowflake:
    enabled: true
    share:
      converter:
        type: radix

simba:
  redis:
    enabled: true
