spring:
  cloud:
    govern:
      discovery:
        registry:
          weight: 18
  web:
    resources:
      static-locations: file:./dashboard/dist/dashboard
  servlet:
    multipart:
      max-file-size: 10MB
