name: Sync to Gitee
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
      - gh-pages
      - gh-pages-with-site-base
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@c44c68aebe42de49a80a8dfd557416b6a0cafdad # master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:Ahoo-Wang/CoSky.git"
          destination-repo: "git@gitee.com:AhooWang/CoSky.git"